name: service-connection-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Bicep file
    - name: Deploy Service Connection
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
        resourceGroupName: ${{ secrets.AZUREREGION }}
        template: ./serviconnection.bicep.bicep
        parameters: 'devOpsOrganizationName=azuredevopst patToken=5q47ozznl24doyze3z763na7ig3qiaivohtxkxkdhybub2scpc4a'
        failOnStdErr: false
