on:
  workflow_dispatch:
  
name: Azure-bicep-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./  # Checkout to the root directory
        
    - name: Deploy ADF Bicep Template
      run: |
        az deployment sub create --location "East US" \
        --template-file example.bicep \
        --parameters adf.json
        --subscription 7b44425c-979b-476a-9cca-cd73b2fcff42 \
        --resource-group my-test-dev
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
