on:
  workflow_dispatch:
  
name: Azure-bicep-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v3
      # If your files are in the root of the repository, you might not need the next line
      with:
          path: master  
    
    - name: Deploy ADF Bicep Template
      run: |
        az deployment sub create --location "East US" \
        --template-file example.bicep \
        --parameters adf.json

      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
