on:
  workflow_dispatch:
  
name: Azure-arm-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./  # Checkout to the root directory

    - name: Deploy ARM Template
      id: arm
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: 7b44425c-979b-476a-9cca-cd73b2fcff42
        region: East US
        resourceGroupName: my-test-dev
        template: example.bicep
        failOnStdErr: true
