name: adf-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Use Azure Login Service Connection
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'  # Reference the Service Connection secret

      # Debug: Display environment variables
      - name: Debug Environment Variables
        run: |
          echo "TEMPLATEFILE: $TEMPLATEFILE"
          echo "AZURE_SUBSCRIPTIONID: $AZURE_SUBSCRIPTIONID"
          echo "AZURE_AZUREREGION: $AZURE_AZUREREGION"

      # Deploy ARM template with environment variables
      - name: Deploy ARM Template
        id: arm
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTIONID }}
          region: ${{ env.AZURE_AZUREREGION }}
          resourceGroupName: my-test-dev
          template: ${{ env.TEMPLATEFILE }}
          failOnStdErr: true
        env:
          ENV: dev
